# Generated by Django 4.1 on 2022-08-17 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_apply'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='apply',
            table='apply',
        ),
    ]
