# Generated by Django 4.1 on 2022-08-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nation', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
    ]
