# Generated by Django 4.1 on 2022-08-17 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_announcement'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='announcement',
            table='announcements',
        ),
    ]
