# Generated by Django 4.1 on 2022-08-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_announcement_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='compensation',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
    ]
